# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeScanner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'ZBarSDK', '~> 1.3.1'

  # Pods for CodeScanner

end
